// Mocks generated by Mockito 5.1.0 from annotations
// in cowpay/test/features/data/datasources/remote_data_source_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:cowpay/core/network/network_util.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [NetworkUtil].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkUtil extends _i1.Mock implements _i2.NetworkUtil {
  MockNetworkUtil() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<dynamic> getList(String? url) =>
      (super.noSuchMethod(Invocation.method(#getList, [url]),
          returnValue: Future<dynamic>.value()) as _i3.Future<dynamic>);
  @override
  _i3.Future<dynamic> postWithRaw(String? url, {Map<dynamic, dynamic>? body}) =>
      (super.noSuchMethod(Invocation.method(#postWithRaw, [url], {#body: body}),
          returnValue: Future<dynamic>.value()) as _i3.Future<dynamic>);
  @override
  _i3.Future<dynamic> postLogout(String? url, {Map<dynamic, dynamic>? body}) =>
      (super.noSuchMethod(Invocation.method(#postLogout, [url], {#body: body}),
          returnValue: Future<dynamic>.value()) as _i3.Future<dynamic>);
  @override
  _i3.Future<dynamic> put(String? url, {Map<dynamic, dynamic>? body}) =>
      (super.noSuchMethod(Invocation.method(#put, [url], {#body: body}),
          returnValue: Future<dynamic>.value()) as _i3.Future<dynamic>);
  @override
  _i3.Future<dynamic> delete(String? url, {Map<dynamic, dynamic>? body}) =>
      (super.noSuchMethod(Invocation.method(#delete, [url], {#body: body}),
          returnValue: Future<dynamic>.value()) as _i3.Future<dynamic>);
  @override
  _i3.Future<dynamic> postUrlEncoded(String? url,
          {Map<dynamic, dynamic>? body, dynamic encoding}) =>
      (super.noSuchMethod(
          Invocation.method(
              #postUrlEncoded, [url], {#body: body, #encoding: encoding}),
          returnValue: Future<dynamic>.value()) as _i3.Future<dynamic>);
  @override
  _i3.Future<dynamic> putGetToken(String? url,
          {Map<dynamic, dynamic>? body, dynamic encoding}) =>
      (super.noSuchMethod(
          Invocation.method(
              #putGetToken, [url], {#body: body, #encoding: encoding}),
          returnValue: Future<dynamic>.value()) as _i3.Future<dynamic>);
  @override
  _i3.Future<dynamic> get(String? url) =>
      (super.noSuchMethod(Invocation.method(#get, [url]),
          returnValue: Future<dynamic>.value()) as _i3.Future<dynamic>);
}
