// Mocks generated by Mockito 5.1.0 from annotations
// in cowpay/test/features/data/datasources/remote_data_source_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:api_manager/api_manager.dart' as _i3;
import 'package:api_manager/failures.dart' as _i5;
import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeEither_0<L, R> extends _i1.Fake implements _i2.Either<L, R> {}

/// A class which mocks [APIsManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockAPIsManager extends _i1.Mock implements _i3.APIsManager {
  @override
  _i4.Future<_i2.Either<_i5.Failure, R>> send<R, ER extends _i3.ResponseModel>(
          {_i3.Request? request,
          R Function(Map<String, dynamic>)? responseFromMap,
          ER Function(Map<String, dynamic>)? errorResponseFromMap}) =>
      (super.noSuchMethod(
              Invocation.method(#send, [], {
                #request: request,
                #responseFromMap: responseFromMap,
                #errorResponseFromMap: errorResponseFromMap
              }),
              returnValue: Future<_i2.Either<_i5.Failure, R>>.value(
                  _FakeEither_0<_i5.Failure, R>()))
          as _i4.Future<_i2.Either<_i5.Failure, R>>);
}
